name: Deploy static content to Pages
on:
  push:
    path:
      - 'docs/**'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Change to docs directory
        run: cd docs

      - name: Set Node and PNPM
        uses: actions/setup-node@v4.0.1

      - name: Install PNPM
        run: |
          cd docs
          npm -g i pnpm

      - name: Install dependencies
        run: |
          cd docs
          pnpm install

      - name: Build
        run: |
          cd docs
          pnpm build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './docs/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
